### ISSUE TITLE
is this package being maintained?

### ISSUE THREAD

**Issue by shayandavoodii** [BenLauwens/ResumableFunctions.jl#56]

**Comment by hdavid16** [comment]
Not really, which is quite unfortunate

**Comment by Krastanov** [comment]
I believe Ben, the original author, might not have the bandwidth to work on ResumableFunctions these days. Thus, I forked the repository into a new Semicoroutines.jl https://github.com/QuantumSavory/Semicoroutines.jl in order to support 1.10 and future julia versions.

As this library is an important part of another project of mine, I plan to provide support at least for the next few years. I am certainly interested in having help from other contributors (and maybe merging things back here if ResumableFunctions.jl is revided).

A similar fork is being prepared for SimJulia

**Comment by hdavid16** [comment]
Good idea. What do you think about having the fork of SimJulia in the JuliaDynamics community? We just moved another discrete event simulation package over there: DiscreteEvents.jl

**Comment by Krastanov** [comment]
That sounds good! I will email you directly to discuss the logistics.

**Comment by Krastanov** [comment]
As discussed in https://github.com/BenLauwens/ResumableFunctions.jl/issues/60 , there are now a few volunteers that will be supporting the package in the near term.
